server {
    server_name customer.magneqtransmission.com;  # your domain

    # Backend API
    location /server/ {
        proxy_pass http://127.0.0.1:5000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
        root /home/ubuntu/frontend-prod/dist;
        index index.html;
    # Frontend (production build)
    location / {
        try_files $uri $uri/ /index.html;
    }
location /assets/ {
        root /home/ubuntu/frontend-prod/dist;
        expires 1y;
        add_header Cache-Control "public";
}
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/customer.magneqtransmission.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/customer.magneqtransmission.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    listen 80;
    server_name customer.magneqtransmission.com;
    return 301 https://$host$request_uri;
}